name: my-first-github-action
on: [push]
jobs:
 build-project:
  runs-on: ubuntu-latest
  steps:
   - run: echo 'copy repository to docker container'
   - uses: actions/checkout@v3
   - run: echo 'copied!'
   - run: tree
