name: my-first-github-action
on: [push]
jobs:
 print-hello-world:
  runs-on: ubuntu-latest
  steps:
   - run: echo 'hello world!'
   - run: echo 'step 1 done...'
   - run: echo 'step 2 starts...'
   - run: echo 'checking github settings'
